[package]
name = "rust-yew"
version = "0.1.0"
authors = ["rawblue-sudo <56031736+rawblue-sudo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
